#!/bin/bash
# This is a simple build script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

echo "DEPLOY DJANGO"
PROJECT_PATH=$OPENSHIFT_REPO_DIR
touch $PROJECT_PATH/teste.txt
# $PROJECT_PATH/manage.py migrate --settings='rover.settings' 
mkdir $PROJECT_PATH/wsgi/static -p
$PROJECT_PATH/manage.py collectstatic -c --noinput --settings='rover.settings' 
####

# Verifica se existe o diretorio /media
if [ ! -d $OPENSHIFT_DATA_DIR/static ]; then
    mkdir $OPENSHIFT_DATA_DIR/static
fi

# Verifica se existe o diretorio /media/uploads
if [ ! -d $OPENSHIFT_DATA_DIR/static/media/uploads ]; then
    mkdir $OPENSHIFT_DATA_DIR/static/media/uploads -p
    # App Campotec
    #mkdir $OPENSHIFT_DATA_DIR/media/uploads/campotec/homepage -p
    #mkdir $OPENSHIFT_DATA_DIR/media/uploads/campotec/import_inscription -p
    #mkdir $OPENSHIFT_DATA_DIR/media/uploads/campotec/programation -p
    #mkdir $OPENSHIFT_DATA_DIR/media/uploads/campotec/specialty -p
    # App eventos
    mkdir $OPENSHIFT_DATA_DIR/static/media/uploads/eventos/evento -p
    mkdir $OPENSHIFT_DATA_DIR/static/media/uploads/eventos/programacao -p
fi

ln -s $OPENSHIFT_DATA_DIR/static/media/ $OPENSHIFT_REPO_DIR/wsgi/static/media
#ln -s $OPENSHIFT_DATA_DIR/static $OPENSHIFT_REPO_DIR/wsgi/static/
#ln -s $OPENSHIFT_DATA_DIR/static $OPENSHIFT_REPO_DIR/wsgi/
#ln -s $OPENSHIFT_DATA_DIR/ $OPENSHIFT_REPO_DIR/wsgi
